export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_BOARDS = 'GET_ALL_BOARDS';
export const BOARD_GET_FAILED = 'BOARD_GET_FAILED';

export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_CARD = 'CREATE_CARD';

export const GET_COLUMNS_BY_BOARD = 'GET_COLUMNS_BY_BOARD';

export const GET_CARDS_BY_COLUMN = 'GET_CARDS_BY_COLUMN';
export const CREATE_COL = 'CREATE_COL';

export const REORDER_CARD_SAME_COL = 'REORDER_CARD_SAME_COL';
export const REORDER_CARD_DIFFERENT_COL = 'REORDER_CARD_DIFFERENT_COL';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
